spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#url de conexão com o banco
spring.datasource.username=postgres
spring.datasource.password=Vick3991
spring.jpa.hibernate.ddl-auto=update
#ao criar as tabelas e coluna na aplicação ele vai atualizando automagicamente a base

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#para desabilitar a buscar de metadados ao iniciar o hibernate